### PR TITLE
Update download links to v0.7.9

### PR DESCRIPTION
**Pull request by adamgrieger**

### CODE REVIEW

**Comment by ada-hall** [comment]
Is there a reason we aren't just pointing to `octoml_latest.zip` and other routes like that?

**Comment by adamgrieger** [comment]
> Is there a reason we aren't just pointing to `octoml_latest.zip` and other routes like that?

That would make sense to me. That decision probably wouldn't be mine to make; mostly following the runbook at this point.

**Comment by ada-hall** [comment]
Updated the route after I checked the accuracy. I'll approve it for now, but this should probably be revisited

**Review by ada-hall — APPROVED** [review]

**Comment by imalsogreg** [comment]
IIRC the concern with pointing to CLI's `latest` was that `latest` moves more quickly than these tutorials. The version pinning done in the tutorials ensures that the tutorial code is internally consistent (meaning, the commands in the tutorial work when executed with the CLI provided by the tutorial).

If the CLI has tests that ensure that the these tutorials remain accurate after a CLI change, then it'd make sense to point the docs to `latest`.

**Review by jbhsieh — APPROVED** [review]

**Pull request merged**
