### PR TITLE
Bump version to 0.7.2

### PR DESCRIPTION
**Pull request by audhocs**
Includes several of the major changes since v0.6.2

### CODE REVIEW

**Comment by audhocs** [comment]
Currently waiting for CLI release to see if PR checks will pass

**Review by vanessahlyan — COMMENTED** [review]
We should explain to the user what the -s flag does

**Review by vanessahlyan — APPROVED** [review]

**Comment by vanessahlyan** [comment]
also can i assume, that when i run octoml package -h (aka help mode) that i will see explanations about the new flags?

**Comment by audhocs** [comment]
> also can i assume, that when i run octoml package -h (aka help mode) that i will see explanations about the new flags?

@vanessahlyan  yep! here's the menu:

```
$ cargo run -- package -h
    Finished dev [unoptimized + debuginfo] target(s) in 1.85s
     Running `target/debug/octoml package -h`
octoml-package 
Package models defined in input configuration file.

`octoml package` requires an input configuration file. You can run `octoml init` to create the file
using a help wizard, or manually create the file yourself in YAML, JSON, or TOML format yourself. A
minimal example `octoml.yaml` file for unaccelerated packaging looks like the following:

  ---
  models:
    my_model:
      path: mnist-8.mnist

If you wish to use `package` in accelerated mode, additionally run `octoml add -t` before calling
`octoml package -a` or `octoml package -x`

USAGE:
    octoml package [OPTIONS]

OPTIONS:
    -a, --accelerate
            Explore acceleration strategies and return best-performing deployable package after
            acceleration. We recommend running `octoml init` and `octoml add -t` before this command
            to ensure you have all requisite fields for acceleration in the input configuration
            file. Acceleration may take several minutes to complete

    -h, --help
            Print help information

        --ignore-cache
            Ignore the local on disk cache, which incrementalizes OctoML Platform workflows

    -o, --output-directory <OUTPUT_DIRECTORY>
            Control the output directory of packages

    -s, --stream
            Indicates to the CLI to write data to STDOUT. Useful when chaining multiple commands
            together

    -x, --extended
            Full acceleration takes several hours to complete, exploring advanced acceleration
            options in addition to the ones explored by normal acceleration
```

**Review by jbhsieh — APPROVED** [review]
lgtm

**Pull request merged**
